import UserProvider from "@/app/components/UserProvider";
import { NavbarDefault } from "@/app/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cash Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarDefault />
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  );
}
